---
name: Net-Mollom
version: 0.06
author:
  - 'Michael Peters <mpeters@plusthree.com>'
abstract: interface with Mollom web API
license: perl
resources:
  license: ~
requires:
  Any::Moose: 0
  DateTime: 0
  Digest::HMAC_SHA1: 0
  MIME::Base64: 0
  Params::Validate: 0
  XML::RPC: 0.9
build_requires:
  Test::More: 0
provides:
  Net::Mollom:
    file: lib/Net/Mollom.pm
    version: 0.06
  Net::Mollom::ContentCheck:
    file: lib/Net/Mollom/ContentCheck.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
