---
abstract: 'interface with Mollom web API'
author:
  - 'Michael Peters <mpeters@plusthree.com>'
build_requires:
  Exception::Class::TryCatch: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Mollom
provides:
  Net::Mollom:
    file: lib/Net/Mollom.pm
    version: 0.08
  Net::Mollom::ContentCheck:
    file: lib/Net/Mollom/ContentCheck.pm
requires:
  Any::Moose: 0
  DateTime: 0
  Digest::HMAC_SHA1: 0
  Exception::Class: 0
  MIME::Base64: 0
  Params::Validate: 0
  XML::RPC: 0.9
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
